# Site settings
title: Nika Kurashvili
name: Nika Kurashvili

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/nnikka
 - title: LinkedIn
   url: https://www.linkedin.com/in/nika-kurashvili-b28289165/

#Any buzzword skills you want to include
skills:
 - Java
 - C
 - C++
 - Node.js
 - PHP
 - Laravel
 - Javascript   
 - React
 - Vue
 - Angular
 - jQuery
 - Cordova
 - Ionic
 - SQL
 - MySQL
 - NoSQL
 - MongoDB
 - Redis
 - REST API
 - Linux(ubuntu)
 - Apache
 - Nginx
 - Docker
 - Solidity
 - Smart contracts
 - Hyperledger

#Work experience is required
roles:
 - title: Full-stack developer
   start: 2018
   end: Ongoing
   employer: Birtvi
   description: Working as a Full-stack developer by creating complex applications and white papers based on blockchain technology.
 - title: Full-stack developer
   start: 2016
   end: Ongoing
   employer: Kairos Logistic
   description: Working as a full-stack web and mobile developer by creating live-tracking application
 - title: Front-end developer
   start: 2015
   end: 2016
   employer: Dolphin software
   description: Working as a front-end developer by creating the application for bank controll panel. 

#Education is required
education:
 - level: Bachelor of Computer Engineering
   date: 2018
   subject: Computer Science and Engineering
   school: Free University Of Tbilisi, Georgia
 - level: Graduation of School
   date: 2014
   subject: Strong Skills In Math And Physics
   school: Physics and Mathematics School in Georgia, Kutaisi
   
#This section is optional (as is the image link below)
coursera:
   courses:
    - title: Proofus
      link: http://test.proofus.com/
      optionalimage: ./img/proofus.PNG
      date: 
    - title: Bene-exclusive
      link: http://bene-exclusive.com/
      optionalimage: ./img/bene.PNG
      date: 
    - title: Translive
      link: http://beta.translive.ge/
      optionalimage: ./img/translive.PNG
      date: 


