# Site settings
title: Nika Kurashvili
name: Nika Kurashvili

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/nnikka
 - title: LinkedIn
   url: https://www.linkedin.com/in/nika-kurashvili-b28289165/

#Any buzzword skills you want to include
skills:
 - Java
 - C
 - C++
 - Node.js
 - PHP
 - Laravel
 - Javascript   
 - React
 - Vue
 - Angular
 - jQuery
 - Cordova
 - Ionic
 - SQL
 - MySQL
 - NoSQL
 - MongoDB
 - Redis
 - REST API
 - Linux(ubuntu)
 - Apache
 - Nginx
 - Solidity
 - Smart contracts

#Work experience is required
roles:
 - title: Senior Software Engineer
   start: 2018
   end: Ongoing
   employer: Bitforx
   description: Working as a senior software engineer by creating complex applications and white papers based on blockchain technology.
 - title: Full-stack developer
   start: 2017
   end: Ongoing
   employer: Kairos Logistic
   description: Working as a full-stack web and mobile developer by creating live-tracking application
 - title: Front-end developer
   start: 2016
   end: 2017
   employer: Dolphin software
   description: Working as a front-end developer by creating the application for bank controll panel. 

#Education is required
education:
 - level: Bachelor of Computer Engineering
   date: 2018
   subject: Computer Science and Engineering
   school: Free University Of Tbilisi, Georgia
 - level: Graduation of School
   date: 2015
   subject: Strong Skills In Math And Physics
   school: Physics and Mathematics School in Georgia, Kutaisi
   
#This section is optional (as is the image link below)
coursera:
   courses:
    - title: Bene-exclusive
      link: http://bene-exclusive.com/
      optionalimage: https://lh3.google.com/u/0/d/15P7hykyfyKbKS5zgbNc220EIhIekW_SL=w200-h150-p-k-nu-iv1
      date: 
    - title: Teleport Georgia
      link: http://teleportgeorgia.com/
      optionalimage: https://lh3.google.com/u/0/d/1eJINuGIja8gi1lAmakYsGB7DxxiIkVOu=w200-h150-p-k-nu-iv1
      date: 


